### ISSUE TITLE
Add Addin to Cake Website for display on site

### ISSUE THREAD

**Issue by gep13** [reicheltp/Cake.HockeyApp#5]
Just wanted to suggest that you make a PR to this repo:

https://github.com/cake-build/website

In order to make your Addin appear in the Cake Documentation here:

http://cakebuild.net/dsl

An example of what is required is here:

https://github.com/cake-build/website/pull/20

Let me know if you have any questions.

**Comment by reicheltp** [comment]
see cake-build/website#54

**Comment by gep13** [comment]
Noice! :+1:
